SERVER_PORT: 8081
SERVER_SERVER_HEADER: ""
SERVER_ERROR_INCLUDE_MESSAGE: never
SERVER_ERROR_INCLUDE_BINDING_ERRORS: never
SERVER_ERROR_INCLUDE_STACKTRACE: never
SERVER_ERROR_INCLUDE_EXCEPTION: false

BANCS_BASE_URL: http://localhost
BANCS_WEBCLIENT_MAX_CONNECTIONS: 5
BANCS_WEBCLIENT_MAX_IDLE_TIME: 10s
BANCS_WEBCLIENT_PENDING_ACQUIRE_MAX_COUNT: -1
BANCS_WEBCLIENT_PENDING_ACQUIRE_TIMEOUT: 2s
BANCS_WEBCLIENT_MAX_IN_MEMORY_SIZE: 1MB
BANCS_IIB_SUPPORT_ENABLED: false

SPRING_AUTOCONFIGURE_EXCLUDE: io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerAutoConfiguration
SPRING_MAIN_LAZY_INITIALIZATION: true
SPRING_APPLICATION_NAME: tnd-msa-sp-wsclientes0061-local
SPRING_HTTP_REACTIVECLIENT_CONNECTOR: REACTOR
SPRING_HTTP_REACTIVECLIENT_CONNECT_TIMEOUT: 5000
SPRING_HTTP_REACTIVECLIENT_READ_TIMEOUT: 10000
SPRING_HTTP_REACTIVECLIENT_WRITE_TIMEOUT: 10000
SPRING_HTTP_REACTIVECLIENT_RESPONSE_TIMEOUT: 10000
SPRING_HEADER_CHANNEL: digital
SPRING_HEADER_MEDIUM: web

WSCLIENTES0061_VALIDATION_BODY_REQUIRED_CODE: "1"
WSCLIENTES0061_VALIDATION_OPERATION_REQUIRED_CODE: "2"
WSCLIENTES0061_VALIDATION_NATURAL_CUSTOMER_REQUIRED_CODE: "3"
WSCLIENTES0061_VALIDATION_OPERATION_INVALID_CODE: "4"
WSCLIENTES0061_VALIDATION_CUSTOMER_NOT_FOUND_CODE: "0282"
WSCLIENTES0061_VALIDATION_BODY_REQUIRED_MESSAGE: Body input is required
WSCLIENTES0061_VALIDATION_CIF_INVALID_MESSAGE: Valor del campo cif vacío o inválido
WSCLIENTES0061_VALIDATION_CUSTOMER_NOT_FOUND_MESSAGE: NO SE ENCONTRARON REGISTROS DEL CLIENTE
WSCLIENTES0061_VALIDATION_OPERATION_REQUIRED_MESSAGE: Valor del campo operacion vacío o inválido
WSCLIENTES0061_VALIDATION_NATURAL_CUSTOMER_REQUIRED_MESSAGE: Valor del campo clienteNatural vacío o inválido
WSCLIENTES0061_VALIDATION_OPERATION_INVALID_MESSAGE: Valor del campo operacion inválido
WSCLIENTES0061_DOMAIN_DEFAULT_ERROR_MESSAGE: Unexpected domain error

WSCLIENTES0061_SOAP_PATH: /IntegrationBus/soap/WSClientes0061
WSCLIENTES0061_SOAP_TRANSACTION_ID: "061406"
WSCLIENTES0061_SOAP_ERROR_TYPE: ERROR
WSCLIENTES0061_SOAP_FATAL_TYPE: FATAL
WSCLIENTES0061_SOAP_INFO_TYPE: INFO
WSCLIENTES0061_SOAP_DEFAULT_ERROR_CODE: "999"
WSCLIENTES0061_SOAP_INTERNAL_ERROR_CODE: "500"
WSCLIENTES0061_SOAP_MISSING_TELLER_CODE: "9927"
WSCLIENTES0061_SOAP_FAULT_CODE: "soapenv:Server"
WSCLIENTES0061_SOAP_FAULT_MESSAGE_MISSING_TELLER_TAG: "BIP3113E: Exception detected in message flow com.bpichincha.esb.wsclientes0061.WSClientes0061.SOAP Input (integration node TCSBRKR1_BP)"
WSCLIENTES0061_SOAP_DEFAULT_ERROR_MESSAGE: "Unexpected SOAP processing error"
WSCLIENTES0061_SOAP_DEFAULT_BUSINESS_ERROR_MESSAGE: "Existe un inconveniente para ejecutar tu transacción. Por favor intenta más tarde."
WSCLIENTES0061_SOAP_MISSING_TELLER_MESSAGE: "Datos de la cabecera de la transaccion no se han asignado"
WSCLIENTES0061_SOAP_BODY_NULL_MESSAGE: "SOAP body is null"
WSCLIENTES0061_SOAP_OPERATION_NOT_FOUND_MESSAGE: "No valid SOAP operation found in Body"

WSCLIENTES0061_BANCS_NULL_RESPONSE_CODE: BANCS_NULL_RESPONSE
WSCLIENTES0061_BANCS_UNKNOWN_ERROR_CODE: BANCS_UNKNOWN_ERROR
WSCLIENTES0061_BANCS_NULL_BODY_CODE: BANCS_NULL_BODY
WSCLIENTES0061_BANCS_BACKEND_CODE_ESB: "00638"
WSCLIENTES0061_BANCS_BACKEND_CODE_BUSINESS: "00045"
WSCLIENTES0061_BANCS_CONNECTOR_EXCEPTION_CODE: "9928"
WSCLIENTES0061_BANCS_INVOCATION_CODE: "9929"
WSCLIENTES0061_BANCS_TIMEOUT_CODE: "9920"
WSCLIENTES0061_BANCS_HTTP_CODE_SERVICE_UNAVAILABLE: 503
WSCLIENTES0061_BANCS_CONNECTION_ERROR_MESSAGE: "Error de conexión con BANCS"
WSCLIENTES0061_BANCS_NULL_RESPONSE_MESSAGE: "Null response from BANCS core"
WSCLIENTES0061_BANCS_UNKNOWN_ERROR_MESSAGE: "Unknown BANCS response error"
WSCLIENTES0061_BANCS_NULL_BODY_MESSAGE: "BANCS response without body"
WSCLIENTES0061_BANCS_RESPONSE_ERROR_MESSAGE: "Error processing BANCS response"
WSCLIENTES0061_BANCS_CONNECTOR_EXCEPTION_PREFIX: "ESB-%2% "
WSCLIENTES0061_BANCS_INVOCATION_MESSAGE: "Error al invocar transaccion Bancs"
WSCLIENTES0061_BANCS_TIMEOUT_MESSAGE: "Tiempo de espera terminado sin respuesta"

WEB_FILTER_TRACE_ID_HEADER_NAME: x-guid
OPTIMUS_WEB_FILTER_ENABLED: true
OPTIMUS_WEB_FILTER_EXCLUDED_PATH_PATTERNS_DEFAULTS: /actuator/**
OPTIMUS_WEB_HEADERS_ENABLED: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_APP_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_GUID_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_CHANNEL_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_MEDIUM_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_SESSION_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_DEVICE_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_DEVICE_IP_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_AGENCY_FORWARD: true
OPTIMUS_WEB_HEADERS_DEFAULT_X_GEOLOCATION_FORWARD: true

RESILIENCE4J_CIRCUITBREAKER_ENABLED: false
BANCS_CB_WINDOW_SIZE: 20
BANCS_CB_MIN_CALLS: 10
BANCS_CB_FAILURE_RATE: 50
BANCS_CB_WAIT_OPEN: 20s

CGI_TRACE_LOGGER_ENABLED: true
CGI_CUSTOM_LEVEL_ENABLED: false
CGI_CUSTOM_LEVEL_INFO_ENABLED: false
CGI_CUSTOM_LEVEL_DEBUG_ENABLED: false
CGI_CUSTOM_LEVEL_WARN_ENABLED: false
CGI_CUSTOM_LEVEL_ERROR_ENABLED: false
CGI_TRACE_PAYLOAD_MODE: NONE
CGI_TRACE_PAYLOAD_FALLBACK_MODE: EMPTY
CGI_TRACE_METADATA_ENABLED: false

TPL_LOG_INFO: INFO
TPL_LOG_WARN: WARN